// <auto-generated />
using System;
using AsadaLisboaBackend.Models.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AsadaLisboaBackend.Models.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AsadaLisboaBackend.Models.AboutUsSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("character varying(2500)");

                    b.Property<byte>("Order")
                        .HasColumnType("smallint");

                    b.Property<string>("SectionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Order");

                    b.ToTable("AboutUsSections");

                    b.HasData(
                        new
                        {
                            Id = new Guid("71dadbe4-7815-4994-a8da-7ae6154769df"),
                            Content = "La ASADA Urbanización Lisboa surge como una iniciativa comunal ante la necesidad de administrar de forma organizada el sistema de abastecimiento de agua potable de la comunidad. Con el crecimiento de la población y el aumento en la demanda del servicio, los vecinos se organizaron para garantizar una distribución eficiente, segura y continua del recurso hídrico.\nCon el paso del tiempo, la organización ha fortalecido su infraestructura mediante la implementación de pozos, tanques de almacenamiento y redes de distribución, así como el desarrollo de procesos administrativos y financieros que permiten la sostenibilidad del servicio. En la actualidad, la ASADA continúa enfocada en la mejora continua, promoviendo el uso responsable del agua y la participación activa de la comunidad.",
                            Order = (byte)1,
                            SectionType = "Historia"
                        },
                        new
                        {
                            Id = new Guid("e8fa8e42-a5a2-4d94-8110-613f639ad896"),
                            Content = "Brindar el servicio de agua potable a la comunidad de Urbanización Lisboa, garantizando altos estándares de calidad, continuidad y cobertura, mediante una gestión responsable y eficiente de los recursos hídricos y financieros.\nLa organización procura el adecuado mantenimiento, mejora y expansión de la infraestructura del acueducto, asegurando la sostenibilidad del servicio en el tiempo. Asimismo, promueve una atención oportuna y transparente a los abonados, contribuyendo a la salud pública, el bienestar social y el desarrollo integral de la comunidad, bajo principios de equidad, responsabilidad y compromiso ambiental.",
                            Order = (byte)2,
                            SectionType = "Misión"
                        },
                        new
                        {
                            Id = new Guid("02f9cf72-83fd-4df0-ba40-8fd8ae2e9c8e"),
                            Content = "Ser una organización comunal líder en la gestión del recurso hídrico a nivel local, reconocida por su eficiencia operativa, transparencia administrativa y compromiso con la sostenibilidad ambiental. La ASADA Urbanización Lisboa aspira a consolidarse como un modelo de referencia en la administración de servicios de agua potable, incorporando mejoras continuas en sus procesos, tecnología e infraestructura. Busca garantizar el acceso seguro y sostenible al agua para las generaciones presentes y futuras, fortaleciendo la participación comunitaria y fomentando una cultura de uso responsable del recurso hídrico.",
                            Order = (byte)3,
                            SectionType = "Visión"
                        },
                        new
                        {
                            Id = new Guid("8c764a82-e07b-4f86-be81-dbb7a4478a7e"),
                            Content = "La ASADA Urbanización Lisboa se encarga de administrar, operar y mantener el sistema de acueducto comunal, asegurando la captación, almacenamiento y distribución del agua potable hacia los usuarios. Asimismo, gestiona la facturación y el cobro del servicio, brinda atención a los abonados, ejecuta labores de mantenimiento preventivo y correctivo en la infraestructura, y vela por la calidad del agua suministrada.\nParalelamente, cumple funciones administrativas y financieras, incluyendo la elaboración de informes, la organización de asambleas y el cumplimiento de regulaciones vigentes, además de promover el uso responsable del recurso hídrico y la protección del entorno ambiental.",
                            Order = (byte)4,
                            SectionType = "Funciones"
                        });
                });

            modelBuilder.Entity("AsadaLisboaBackend.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("03e622ec-438b-49f3-8c53-3a3873651c16"),
                            Name = "Proyectos Ejecutados"
                        },
                        new
                        {
                            Id = new Guid("6da5cf2d-e946-43ed-a092-d5b4c9282ffa"),
                            Name = "Estados Financieros"
                        },
                        new
                        {
                            Id = new Guid("3643cd9f-99fe-4873-85f9-2a7b6b4dac28"),
                            Name = "Tanque Principal"
                        },
                        new
                        {
                            Id = new Guid("f62ed863-70d4-446b-9088-10efd6cb6c77"),
                            Name = "Pozo Principal"
                        },
                        new
                        {
                            Id = new Guid("77607c99-2ed1-4b8e-89cc-ccc7c6344e53"),
                            Name = "Lineamientos"
                        },
                        new
                        {
                            Id = new Guid("2b3b492d-e243-4fc8-8217-03ea9998a201"),
                            Name = "Sugerencias"
                        },
                        new
                        {
                            Id = new Guid("ba84f8ac-ead7-4cb3-83b4-77238df95884"),
                            Name = "Solicitudes"
                        },
                        new
                        {
                            Id = new Guid("93ca9020-78fd-4080-8d57-469eb05d9dc3"),
                            Name = "Reglamentos"
                        },
                        new
                        {
                            Id = new Guid("783e94bc-4748-4223-a150-8892354b865b"),
                            Name = "Colindancia"
                        },
                        new
                        {
                            Id = new Guid("560841fb-884b-45f6-9a09-18d4641b7af5"),
                            Name = "Hidrantes"
                        },
                        new
                        {
                            Id = new Guid("5aa04636-cd02-4184-bbe0-603a2e785988"),
                            Name = "Convenios"
                        },
                        new
                        {
                            Id = new Guid("81f11c15-3556-40be-8074-a6be7a5d5ab4"),
                            Name = "Informes"
                        },
                        new
                        {
                            Id = new Guid("ceb0bb8a-0414-474c-b378-46491b4c08e8"),
                            Name = "Exámenes"
                        },
                        new
                        {
                            Id = new Guid("b2dbcf36-fddf-4752-b39d-b31f61e704a3"),
                            Name = "Estudios"
                        },
                        new
                        {
                            Id = new Guid("71b9c756-b148-4e0f-a5c7-09a8a7aa209e"),
                            Name = "Dudas"
                        });
                });

            modelBuilder.Entity("AsadaLisboaBackend.Models.Charge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Charges");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0feb0b33-cf81-4973-9754-e45de997069d"),
                            Name = "Administrador"
                        },
                        new
                        {
                            Id = new Guid("7d591140-46fa-47a3-9875-d450896c8b14"),
                            Name = "Vicepresidente"
                        },
                        new
                        {
                            Id = new Guid("56f6b0c4-9e67-4cb6-ac31-d95ac0d10271"),
                            Name = "Presidente"
                        },
                        new
                        {
                            Id = new Guid("1bce957a-451a-425a-b438-58c0227ff9fc"),
                            Name = "Secretario"
                        },
                        new
                        {
                            Id = new Guid("c8fcb329-dcaf-4352-80fc-5cc7730482e7"),
                            Name = "Tesorero"
                        },
                        new
                        {
                            Id = new Guid("9db79916-bac2-479a-84a1-dfb13c83dda8"),
                            Name = "Vocal 1"
                        },
                        new
                        {
                            Id = new Guid("64849ca6-6daa-4174-a240-a640cd09509f"),
                            Name = "Vocal 2"
                        },
                        new
                        {
                            Id = new Guid("28524859-89fd-4f06-a39c-c62150c1284c"),
                            Name = "Vocal 3"
                        },
                        new
                        {
                            Id = new Guid("bee47254-066c-414b-a872-3cc72d708a67"),
                            Name = "Fiscal"
                        });
                });

            modelBuilder.Entity("AsadaLisboaBackend.Models.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<byte>("Order")
                        .HasColumnType("smallint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Order");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0ac0c004-b812-4f29-855f-5813e89146d9"),
                            ContactType = "Correo electrónico",
                            Order = (byte)1,
                            Value = "asadaurblisboa@gmail.com"
                        },
                        new
                        {
                            Id = new Guid("cee070c5-4fa6-40a3-ae12-db5f2ea8bad1"),
                            ContactType = "Teléfono Celular",
                            Order = (byte)2,
                            Value = "+506 8459-5494"
                        },
                        new
                        {
                            Id = new Guid("a78f2955-59b4-4c88-a429-b9644b19552c"),
                            ContactType = "Teléfono Fijo",
                            Order = (byte)3,
                            Value = "+506 2433-3882"
                        },
                        new
                        {
                            Id = new Guid("491d6c63-98f0-44f9-b837-ff9640d01921"),
                            ContactType = "Ubicación",
                            Order = (byte)4,
                            Value = "https://maps.app.goo.gl/7vArCkz5iEG5abq48"
                        },
                        new
                        {
                            Id = new Guid("37dd984f-7059-48ae-a6d5-cf57d8c2667b"),
                            ContactType = "Facebook",
                            Order = (byte)5,
                            Value = "https://www.facebook.com/asadalisboa/"
                        },
                        new
                        {
                            Id = new Guid("e0b3df15-177c-4581-8fc0-944b205d3b3a"),
                            ContactType = "Horario",
                            Order = (byte)6,
                            Value = "Lunes a viernes: 8:00 a.m. - 12:00 p.m."
                        });
                });

            modelBuilder.Entity("AsadaLisboaBackend.Models.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("DocumentTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("PublicationDate");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("AsadaLisboaBackend.Models.DocumentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Extension")
                        .IsUnique();

                    b.ToTable("DocumentTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d8fbe9b6-1a5e-41ea-98ea-e6641a6047c8"),
                            Extension = ".pdf",
                            MimeType = "application/pdf",
                            Name = "PDF"
                        },
                        new
                        {
                            Id = new Guid("9029eb69-0e77-4cf6-8622-c7902d565745"),
                            Extension = ".docx",
                            MimeType = "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                            Name = "Word"
                        },
                        new
                        {
                            Id = new Guid("1fa5211f-f4ea-42d1-8c5e-dee71d9a75a7"),
                            Extension = ".doc",
                            MimeType = "application/msword",
                            Name = "Word"
                        },
                        new
                        {
                            Id = new Guid("1e42a6e9-0baa-4c51-8812-e459e0678130"),
                            Extension = ".xlsx",
                            MimeType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                            Name = "Excel"
                        },
                        new
                        {
                            Id = new Guid("3f7294fc-4d1c-4a58-8576-9e2d404b2846"),
                            Extension = ".xls",
                            MimeType = "application/vnd.ms-excel",
                            Name = "Excel"
                        },
                        new
                        {
                            Id = new Guid("55931b3a-ae2b-4aec-8625-7c9adbdfab5f"),
                            Extension = ".csv",
                            MimeType = "text/csv",
                            Name = "CSV"
                        },
                        new
                        {
                            Id = new Guid("d9ec3706-86f8-4c3d-a770-e3e38221a7e8"),
                            Extension = ".txt",
                            MimeType = "text/plain",
                            Name = "Texto"
                        },
                        new
                        {
                            Id = new Guid("f4365613-d7e7-488e-b24e-4834645408d6"),
                            Extension = ".zip",
                            MimeType = "application/octet-stream",
                            Name = "ZIP"
                        });
                });

            modelBuilder.Entity("AsadaLisboaBackend.Models.IdentityModels.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("864c6f86-5fdf-4279-857b-d7b8d99170b2"),
                            ConcurrencyStamp = "864C6F86-5FDF-4279-857B-D7B8D99170B2",
                            Name = "Administrador",
                            NormalizedName = "ADMINISTRADOR"
                        },
                        new
                        {
                            Id = new Guid("6fcf3478-3ced-400b-92a6-dbe6a9d37446"),
                            ConcurrencyStamp = "6FCF3478-3CED-400B-92A6-DBE6A9D37446",
                            Name = "Escritor",
                            NormalizedName = "ESCRITOR"
                        },
                        new
                        {
                            Id = new Guid("caa2cbcd-3a76-4ed0-ab4f-7d07034692eb"),
                            ConcurrencyStamp = "CAA2CBCD-3A76-4ED0-AB4F-7D07034692EB",
                            Name = "Lector",
                            NormalizedName = "LECTOR"
                        });
                });

            modelBuilder.Entity("AsadaLisboaBackend.Models.IdentityModels.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ChargeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstLastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime>("RefreshTokenExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecondLastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ChargeId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AsadaLisboaBackend.Models.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PublicationDate");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("AsadaLisboaBackend.Models.New", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("LastEditionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("PublicationDate");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.ToTable("News");
                });

            modelBuilder.Entity("AsadaLisboaBackend.Models.Status", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2c36a4b8-de3e-4607-9b7b-dbe0f0e00390"),
                            Name = "Borrador"
                        },
                        new
                        {
                            Id = new Guid("5c1cebda-fc8c-44ac-997c-aaf015572d46"),
                            Name = "Publicado"
                        });
                });

            modelBuilder.Entity("AsadaLisboaBackend.Models.VisualSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte>("Order")
                        .HasColumnType("smallint");

                    b.Property<string>("SettingType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Order");

                    b.ToTable("VisualSettings");
                });

            modelBuilder.Entity("CategoryDocument", b =>
                {
                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentsId")
                        .HasColumnType("uuid");

                    b.HasKey("CategoriesId", "DocumentsId");

                    b.HasIndex("DocumentsId");

                    b.ToTable("DocumentsCategories", (string)null);
                });

            modelBuilder.Entity("CategoryImage", b =>
                {
                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ImagesId")
                        .HasColumnType("uuid");

                    b.HasKey("CategoriesId", "ImagesId");

                    b.HasIndex("ImagesId");

                    b.ToTable("ImagesCategories", (string)null);
                });

            modelBuilder.Entity("CategoryNew", b =>
                {
                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NewsId")
                        .HasColumnType("uuid");

                    b.HasKey("CategoriesId", "NewsId");

                    b.HasIndex("NewsId");

                    b.ToTable("NewsCategories", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AsadaLisboaBackend.Models.Document", b =>
                {
                    b.HasOne("AsadaLisboaBackend.Models.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AsadaLisboaBackend.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("AsadaLisboaBackend.Models.IdentityModels.ApplicationUser", b =>
                {
                    b.HasOne("AsadaLisboaBackend.Models.Charge", "Charge")
                        .WithMany()
                        .HasForeignKey("ChargeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Charge");
                });

            modelBuilder.Entity("AsadaLisboaBackend.Models.Image", b =>
                {
                    b.HasOne("AsadaLisboaBackend.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("AsadaLisboaBackend.Models.New", b =>
                {
                    b.HasOne("AsadaLisboaBackend.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("CategoryDocument", b =>
                {
                    b.HasOne("AsadaLisboaBackend.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AsadaLisboaBackend.Models.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CategoryImage", b =>
                {
                    b.HasOne("AsadaLisboaBackend.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AsadaLisboaBackend.Models.Image", null)
                        .WithMany()
                        .HasForeignKey("ImagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CategoryNew", b =>
                {
                    b.HasOne("AsadaLisboaBackend.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AsadaLisboaBackend.Models.New", null)
                        .WithMany()
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("AsadaLisboaBackend.Models.IdentityModels.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("AsadaLisboaBackend.Models.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("AsadaLisboaBackend.Models.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("AsadaLisboaBackend.Models.IdentityModels.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AsadaLisboaBackend.Models.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("AsadaLisboaBackend.Models.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
